CREATE TABLE CUSTOMER_UPDATE_LOG
(
    UTC_ID NUMBER,
    UTC_OLD_NAME VARCHAR2(100),
    UTC_NEW_NAME VARCHAR2(100),
    UTC_UPDATED_BY VARCHAR2(100),
    UTC_UPDATE_DATE DATE
);

CREATE TABLE CUSTOMER_TABLE_DELETE_LOG
(
    DTC_ID NUMBER,
    DTC_NAME VARCHAR2(100),
    DTC_ADDRESS VARCHAR2(100),
    DTC_WEBSITE VARCHAR2(100),
    DTC_CREDIT_LIMIT NUMBER(8, 2),
    DTC_DELETED_BY VARCHAR2(100),
    DTC_DELETE_DATE DATE

);